version: '3'
services:

  #MySQL Service
  db:
    image: mysql:5.7.24
    container_name: starvnavi_mysql
    ports:
      - "7777:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql